### PR TITLE
use default import for constants

### LINKED ISSUE #62: fastfile@0.0.20 seems to have falowing error Note that on snarkjs that uses fastfile@0.0.19 does not have this issue
./node_modules/fastfile/src/fastfile.js
Can't import the named export 'O_TRUNC' (imported as 'O_TRUNC') from default-exporting module (only default export is available)

Import trace for requested module:
./node_modules/snarkjs/src/powersoftau_export_challenge.js
./node_modules/snarkjs/src/powersoftau.js
./node_modules/snarkjs/main.js

./node_modules/fastfile/src/fastfile.js
Can't import the named export 'O_CREAT' (imported as 'O_CREAT') from default-exporting module (only default export is available)

Import trace for requested module:
./node_modules/snarkjs/src/powersoftau_export_challenge.js
./node_modules/snarkjs/src/powersoftau.js
./node_modules/snarkjs/main.js

./node_modules/fastfile/src/fastfile.js
Can't import the named export 'O_RDWR' (imported as 'O_RDWR') from default-exporting module (only default export is available)

Import trace for requested module:
./node_modules/snarkjs/src/powersoftau_export_challenge.js
./node_modules/snarkjs/src/powersoftau.js
./node_modules/snarkjs/main.js

./node_modules/fastfile/src/fastfile.js
Can't import the named export 'O_TRUNC' (imported as 'O_TRUNC') from default-exporting module (only default export is available)

Import trace for requested module:
./node_modules/snarkjs/src/powersoftau_export_challenge.js
./node_modules/snarkjs/src/powersoftau.js
./node_modules/snarkjs/main.js

./node_modules/fastfile/src/fastfile.js
Can't import the named export 'O_CREAT' (imported as 'O_CREAT') from default-exporting module (only default export is available)

Import trace for requested module:
./node_modules/snarkjs/src/powersoftau_export_challenge.js
./node_modules/snarkjs/src/powersoftau.js
./node_modules/snarkjs/main.js

### PR DESCRIPTION
**Pull request by mehtaphysical**
Fixes #62.

Use default import for constants and build

### CODE REVIEW

**Comment by mehtaphysical** [comment]
@phated any thoughts on this?

**Comment by phated** [comment]
@mehtaphysical I actually think we want to remove the import on constants because we needed to hack around these at https://github.com/iden3/snarkjs/blob/master/config/rollup.iife.config.js#L10-L17

I think these constants are quite fixed and I'll probably just hardcode them.

**Comment by mehtaphysical** [comment]
Sounds good @phated!

**Comment by phated** [comment]
Fixed by https://github.com/iden3/fastfile/commit/2bca53adcf476b9af6c8e8ec08407c48325cc6f3

**Comment by phated** [comment]
I don't have access, but I've asked Jordi

**Pull request closed without merging**
